# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: GSAK
name: Aakash Sasikumar
email: aakash3697@gmail.com
description: A blog that covers the latest technologies
baseurl: "/gsak" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your siter
root: /
# permalink: pretty

# Logo settings
logo-image-url: images/icon.svg
font-awesome-icon-logo:

# Social settings
github_username: AakashSasikumar
twitter_username:
facebook_URL: https://www.facebook.com/killersamurai
linkedin_url: https://www.linkedin.com/in/aakash-sasikumar/
instagram_username:
dribbble_username:
500px_username:
phone:

# Build settings
markdown: kramdown

# Layout settings
home-link-in-menu: yes

webmaster_verifications:
  google: 02F1Oj_9bwFwBjfZBqElbZSrlqAJs9BaPsnl53MrJsY

plugins:
  - jekyll-seo-tag